# Comparison of Cosine Similarity & K-Nearest Neighbors Models

## Cosine Similarity Model

#### Alternative model for medicine cabinet project using Cosine Similarity to predict cannabis strain recommendations based on user input.

In [1]:
# Imports

import pandas as pd
import numpy as np

In [2]:
# Loading preprocessed data - Courtesy Curdt Million

df = pd.read_csv("lemmatized_strains.csv")

In [3]:
df.head()

Unnamed: 0          Strain    Type  \
0           0          100-Og  hybrid   
1           1  98-White-Widow  hybrid   
2           2            1024  sativa   
3           3        13-Dawgs  hybrid   
4           4        24K-Gold  hybrid   

                                      Effects                     Flavor  \
0  Creative,Energetic,Tingly,Euphoric,Relaxed        Earthy,Sweet,Citrus   
1    Relaxed,Aroused,Creative,Happy,Energetic      Flowery,Violet,Diesel   
2   Uplifted,Happy,Relaxed,Energetic,Creative    Spicy/Herbal,Sage,Woody   
3     Tingly,Creative,Hungry,Relaxed,Uplifted  Apricot,Citrus,Grapefruit   
4   Happy,Relaxed,Euphoric,Uplifted,Talkative       Citrus,Earthy,Orange   

                                         Description  name  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   NaN   
1  The ‘98 Aloha White Widow is an especially pot...   NaN   
2  1024 is a sativa-dominant hybrid bred in Spain...  1024   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   NaN   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   NaN   

                                  ailment  \
0                                     NaN   
1                                     NaN   
2  Stress, Pain, Depression, Inflammation   
3                                     NaN   
4                                     NaN   

                                            all_text  \
0  100-Og hybrid Creative,Energetic,Tingly,Euphor...   
1  98-White-Widow hybrid Relaxed,Aroused,Creative...   
2  1024 sativa Uplifted,Happy,Relaxed,Energetic,C...   
3  13-Dawgs hybrid Tingly,Creative,Hungry,Relaxed...   
4  24K-Gold hybrid Happy,Relaxed,Euphoric,Uplifte...   

                                              lemmas  
0  100-Og hybrid Creative energetic Tingly Euphor...  
1  98-white widow hybrid Relaxed arouse Creative ...  
2  1024 sativa Uplifted happy relaxed energetic C...  
3  13-dawgs hybrid Tingly creative hungry Relaxed...  
4  24k gold hybrid Happy Relaxed Euphoric Uplifte...

In [4]:
# Dropping unnamed columns & resetting index

df = df.drop('Unnamed: 0', axis=1).reset_index()

In [5]:
df.head()

index          Strain    Type                                     Effects  \
0      0          100-Og  hybrid  Creative,Energetic,Tingly,Euphoric,Relaxed   
1      1  98-White-Widow  hybrid    Relaxed,Aroused,Creative,Happy,Energetic   
2      2            1024  sativa   Uplifted,Happy,Relaxed,Energetic,Creative   
3      3        13-Dawgs  hybrid     Tingly,Creative,Hungry,Relaxed,Uplifted   
4      4        24K-Gold  hybrid   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  name  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   NaN   
1  The ‘98 Aloha White Widow is an especially pot...   NaN   
2  1024 is a sativa-dominant hybrid bred in Spain...  1024   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   NaN   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   NaN   

                                  ailment  \
0                                     NaN   
1                                     NaN   
2  Stress, Pain, Depression, Inflammation   
3                                     NaN   
4                                     NaN   

                                            all_text  \
0  100-Og hybrid Creative,Energetic,Tingly,Euphor...   
1  98-White-Widow hybrid Relaxed,Aroused,Creative...   
2  1024 sativa Uplifted,Happy,Relaxed,Energetic,C...   
3  13-Dawgs hybrid Tingly,Creative,Hungry,Relaxed...   
4  24K-Gold hybrid Happy,Relaxed,Euphoric,Uplifte...   

                                              lemmas  
0  100-Og hybrid Creative energetic Tingly Euphor...  
1  98-white widow hybrid Relaxed arouse Creative ...  
2  1024 sativa Uplifted happy relaxed energetic C...  
3  13-dawgs hybrid Tingly creative hungry Relaxed...  
4  24k gold hybrid Happy Relaxed Euphoric Uplifte...

### Vectorizing Words with TF/IDF Vectorizer to Create Document Term Matrix (DTM)

In [6]:
# Instantiating TfidfVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words="english", min_df=0.025, max_df=0.98, ngram_range=(1,3))

In [7]:
# Creating DTM

dtm = vect.fit_transform(df['lemmas'])

In [8]:
# Loading DTM to DataFrame

dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())

In [9]:
dtm.head()

10  10 week      1st   20        50        60   70   80  active  activity  \
0  0.0      0.0  0.00000  0.0  0.400753  0.000000  0.0  0.0     0.0       0.0   
1  0.0      0.0  0.11529  0.0  0.000000  0.000000  0.0  0.0     0.0       0.0   
2  0.0      0.0  0.00000  0.0  0.000000  0.000000  0.0  0.0     0.0       0.0   
3  0.0      0.0  0.00000  0.0  0.000000  0.000000  0.0  0.0     0.0       0.0   
4  0.0      0.0  0.00000  0.0  0.000000  0.172229  0.0  0.0     0.0       0.0   

   ...  variety  way  week  week flower     white  white widow    widow  win  \
0  ...      0.0  0.0   0.0          0.0  0.000000     0.000000  0.00000  0.0   
1  ...      0.0  0.0   0.0          0.0  0.414792     0.530753  0.52785  0.0   
2  ...      0.0  0.0   0.0          0.0  0.000000     0.000000  0.00000  0.0   
3  ...      0.0  0.0   0.0          0.0  0.000000     0.000000  0.00000  0.0   
4  ...      0.0  0.0   0.0          0.0  0.000000     0.000000  0.00000  0.0   

      woody  yield  
0  0.000000    0.0  
1  0.000000    0.0  
2  0.139941    0.0  
3  0.152713    0.0  
4  0.000000    0.0  

[5 rows x 470 columns]

In [10]:
dtm.shape

(2280, 470)

### Applying Cosine Similarity

In [11]:
# Calculating distance of vectors

from sklearn.metrics.pairwise import cosine_similarity

dist_matrix  = cosine_similarity(dtm)

In [12]:
dist_matrix.shape

(2280, 2280)

In [13]:
dist_matrix

array([[1.        , 0.05019954, 0.09446667, ..., 0.04614303, 0.20400223,
        0.03976338],
       [0.05019954, 1.        , 0.03919548, ..., 0.05693017, 0.03774439,
        0.01905132],
       [0.09446667, 0.03919548, 1.        , ..., 0.13120335, 0.03704773,
        0.10142609],
       ...,
       [0.04614303, 0.05693017, 0.13120335, ..., 1.        , 0.18964009,
        0.04080311],
       [0.20400223, 0.03774439, 0.03704773, ..., 0.18964009, 1.        ,
        0.15828765],
       [0.03976338, 0.01905132, 0.10142609, ..., 0.04080311, 0.15828765,
        1.        ]])

In [14]:
# Incorporating distance matrix into dataframe

df_cos = pd.DataFrame(dist_matrix)

In [15]:
df_cos.head()

0         1         2         3         4         5         6     \
0  1.000000  0.050200  0.094467  0.138441  0.167852  0.279632  0.160991   
1  0.050200  1.000000  0.039195  0.062325  0.057198  0.025107  0.062530   
2  0.094467  0.039195  1.000000  0.228735  0.127038  0.019263  0.206242   
3  0.138441  0.062325  0.228735  1.000000  0.142100  0.102130  0.099491   
4  0.167852  0.057198  0.127038  0.142100  1.000000  0.107282  0.111054   

       7         8         9     ...      2270      2271      2272      2273  \
0  0.144329  0.039780  0.151746  ...  0.143444  0.087499  0.138503  0.106033   
1  0.035826  0.037248  0.020530  ...  0.123628  0.047277  0.012108  0.055818   
2  0.080875  0.182667  0.084721  ...  0.143060  0.145247  0.187344  0.149791   
3  0.198146  0.176917  0.124149  ...  0.201189  0.151043  0.137494  0.144705   
4  0.105749  0.096732  0.143729  ...  0.144879  0.102967  0.125487  0.122542   

       2274      2275      2276      2277      2278      2279  
0  0.098898  0.309409  0.082647  0.046143  0.204002  0.039763  
1  0.049122  0.019146  0.045944  0.056930  0.037744  0.019051  
2  0.264191  0.099647  0.154952  0.131203  0.037048  0.101426  
3  0.208115  0.085285  0.188352  0.078144  0.105342  0.237819  
4  0.133906  0.077173  0.081454  0.191653  0.069589  0.077302  

[5 rows x 2280 columns]

In [16]:
df_cos.shape

(2280, 2280)

In [17]:
df.lemmas[0]

'100-Og hybrid Creative energetic Tingly Euphoric Relaxed Earthy Sweet Citrus $ 100 og 50/50 hybrid strain pack strong punch supposedly refer strength high price start show Hollywood plant $ 100 og tend produce large dark green bud stem user report strong body effect indica pain relief alert cerebral feeling thank sativa  '

In [18]:
# Top 5 similar strains to strain index_no. 0 (100-OG)

OG100_top_5 = df_cos[df_cos[0] < 1][0].sort_values(ascending=False)[:5]

In [19]:
OG100_top_5

670     0.456571
2137    0.433465
1837    0.423226
1384    0.420398
1697    0.417113
Name: 0, dtype: float64

In [20]:
type(OG100_top_5)

pandas.core.series.Series

In [21]:
# Converting to dict

OG100_top_5 = dict(OG100_top_5)

In [22]:
type(OG100_top_5)

dict

In [23]:
OG100_top_5

{670: 0.4565706222702947,
 2137: 0.4334652217771763,
 1837: 0.42322601521876946,
 1384: 0.4203984288723379,
 1697: 0.4171133953625684}

In [24]:
OG100_top_5

{670: 0.4565706222702947,
 2137: 0.4334652217771763,
 1837: 0.42322601521876946,
 1384: 0.4203984288723379,
 1697: 0.4171133953625684}

In [25]:
OG100_top_5.keys()

dict_keys([670, 2137, 1837, 1384, 1697])

In [26]:
# Top 5 indexes in DataFrame

df.iloc[[i for i in OG100_top_5], 1:6]

Strain    Type                                    Effects  \
670       Donna-Og  hybrid     Creative,Euphoric,Relaxed,Happy,Hungry   
2137       Tuna-Og  hybrid                                       None   
1837  Skywalker-Og  hybrid     Relaxed,Euphoric,Happy,Uplifted,Sleepy   
1384    Monster-Og  hybrid         Hungry,Relaxed,Happy,Tingly,Sleepy   
1697       Rainbow  hybrid  Euphoric,Relaxed,Happy,Talkative,Uplifted   

                         Flavor  \
670        Citrus,Pungent,Sweet   
2137                       None   
1837       Earthy,Pungent,Sweet   
1384  Woody,Spicy/Herbal,Earthy   
1697        Sweet,Citrus,Orange   

                                            Description  
670   Donna OG is a 50/50 hybrid cross between two O...  
2137  Tuna OG (or OG Tuna Kush) is a 50/50 hybrid cr...  
1837  Skywalker OG is a potent indica-dominant hybri...  
1384  Monster OG from The Green Element is a hybrid ...  
1697  Rainbow is a 50/50 indica/sativa hybrid from S...

### Creating Function to Calculate Closest Related Strains to Each Corresponding Strain

In [27]:
# Creating Lookup Table DataFrame

df_names = df[['index', 'Strain']]

In [28]:
df_names.head()

index          Strain
0      0          100-Og
1      1  98-White-Widow
2      2            1024
3      3        13-Dawgs
4      4        24K-Gold

In [29]:
def cos_sim(x):
    
    """Returns top 5 similar strain indexes corresponding to input index"""
     
    top_5 = dict(df_cos[df_cos[x] < 1][x].sort_values(ascending=False)[:5])
    
    return top_5.keys()


### Creating New Column in DataFrame for Strains with High Cosine Similarities

In [30]:
df_strains = df.copy()

In [31]:
df_strains.head()

index          Strain    Type                                     Effects  \
0      0          100-Og  hybrid  Creative,Energetic,Tingly,Euphoric,Relaxed   
1      1  98-White-Widow  hybrid    Relaxed,Aroused,Creative,Happy,Energetic   
2      2            1024  sativa   Uplifted,Happy,Relaxed,Energetic,Creative   
3      3        13-Dawgs  hybrid     Tingly,Creative,Hungry,Relaxed,Uplifted   
4      4        24K-Gold  hybrid   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  name  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   NaN   
1  The ‘98 Aloha White Widow is an especially pot...   NaN   
2  1024 is a sativa-dominant hybrid bred in Spain...  1024   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   NaN   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   NaN   

                                  ailment  \
0                                     NaN   
1                                     NaN   
2  Stress, Pain, Depression, Inflammation   
3                                     NaN   
4                                     NaN   

                                            all_text  \
0  100-Og hybrid Creative,Energetic,Tingly,Euphor...   
1  98-White-Widow hybrid Relaxed,Aroused,Creative...   
2  1024 sativa Uplifted,Happy,Relaxed,Energetic,C...   
3  13-Dawgs hybrid Tingly,Creative,Hungry,Relaxed...   
4  24K-Gold hybrid Happy,Relaxed,Euphoric,Uplifte...   

                                              lemmas  
0  100-Og hybrid Creative energetic Tingly Euphor...  
1  98-white widow hybrid Relaxed arouse Creative ...  
2  1024 sativa Uplifted happy relaxed energetic C...  
3  13-dawgs hybrid Tingly creative hungry Relaxed...  
4  24k gold hybrid Happy Relaxed Euphoric Uplifte...

In [32]:
df_strains.columns

Index(['index', 'Strain', 'Type', 'Effects', 'Flavor', 'Description', 'name',
       'ailment', 'all_text', 'lemmas'],
      dtype='object')

In [33]:
# Applying Cosine Similarity Function to Data Frame

df_strains['Cos Sim Strains'] = [cos_sim(i) for i in df['index']]

In [34]:
df_strains.sample(5)

index          Strain    Type  \
935     935     Green-Mango  indica   
1579   1579  Pink-Starburst  hybrid   
28       28   Ace-Killer-Og  indica   
510     510          Chicle  hybrid   
2191   2191       Wet-Dream  sativa   

                                         Effects                      Flavor  \
935     Euphoric,Uplifted,Happy,Creative,Relaxed         Citrus,Earthy,Woody   
1579  Euphoric,Happy,Talkative,Uplifted,Creative          Sweet,Diesel,Berry   
28        Relaxed,Sleepy,Euphoric,Happy,Uplifted  Earthy,Diesel,Spicy/Herbal   
510        Aroused,Euphoric,Focused,Happy,Hungry         Ammonia,Diesel,Mint   
2191  Uplifted,Energetic,Happy,Euphoric,Creative   Earthy,Spicy/Herbal,Woody   

                                            Description name ailment  \
935   Green Mango by Sumo Seeds is a tropical indica...  NaN     NaN   
1579  Pink Starburst by Manali West is an ultra pote...  NaN     NaN   
28    Ace Killer OG is an indica strain that boasts ...  NaN     NaN   
510   Chicle (aka Bubbledawg) by T.H. Seeds is an aw...  NaN     NaN   
2191  Wet Dream, native to San Diego, California, is...  NaN     NaN   

                                               all_text  \
935   Green-Mango indica Euphoric,Uplifted,Happy,Cre...   
1579  Pink-Starburst hybrid Euphoric,Happy,Talkative...   
28    Ace-Killer-Og indica Relaxed,Sleepy,Euphoric,H...   
510   Chicle hybrid Aroused,Euphoric,Focused,Happy,H...   
2191  Wet-Dream sativa Uplifted,Energetic,Happy,Euph...   

                                                 lemmas  \
935   Green Mango indica Euphoric Uplifted happy Cre...   
1579  pink Starburst hybrid Euphoric happy talkative...   
28    Ace Killer Og indica Relaxed sleepy Euphoric h...   
510   Chicle hybrid arouse Euphoric Focused happy hu...   
2191  wet dream sativa uplift energetic happy euphor...   

                    Cos Sim Strains  
935   (1340, 1310, 373, 1315, 1314)  
1579   (1579, 788, 653, 1847, 1871)  
28      (1360, 1421, 1540, 417, 26)  
510    (2113, 32, 1746, 1973, 1269)  
2191   (2191, 1276, 1285, 280, 243)

In [35]:
df_strains.head()

index          Strain    Type                                     Effects  \
0      0          100-Og  hybrid  Creative,Energetic,Tingly,Euphoric,Relaxed   
1      1  98-White-Widow  hybrid    Relaxed,Aroused,Creative,Happy,Energetic   
2      2            1024  sativa   Uplifted,Happy,Relaxed,Energetic,Creative   
3      3        13-Dawgs  hybrid     Tingly,Creative,Hungry,Relaxed,Uplifted   
4      4        24K-Gold  hybrid   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  name  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   NaN   
1  The ‘98 Aloha White Widow is an especially pot...   NaN   
2  1024 is a sativa-dominant hybrid bred in Spain...  1024   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   NaN   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   NaN   

                                  ailment  \
0                                     NaN   
1                                     NaN   
2  Stress, Pain, Depression, Inflammation   
3                                     NaN   
4                                     NaN   

                                            all_text  \
0  100-Og hybrid Creative,Energetic,Tingly,Euphor...   
1  98-White-Widow hybrid Relaxed,Aroused,Creative...   
2  1024 sativa Uplifted,Happy,Relaxed,Energetic,C...   
3  13-Dawgs hybrid Tingly,Creative,Hungry,Relaxed...   
4  24K-Gold hybrid Happy,Relaxed,Euphoric,Uplifte...   

                                              lemmas  \
0  100-Og hybrid Creative energetic Tingly Euphor...   
1  98-white widow hybrid Relaxed arouse Creative ...   
2  1024 sativa Uplifted happy relaxed energetic C...   
3  13-dawgs hybrid Tingly creative hungry Relaxed...   
4  24k gold hybrid Happy Relaxed Euphoric Uplifte...   

                 Cos Sim Strains  
0  (670, 2137, 1837, 1384, 1697)  
1   (2240, 237, 820, 2221, 2239)  
2  (1041, 1014, 2171, 620, 1413)  
3      (3, 1026, 1043, 133, 913)  
4  (1498, 1483, 1172, 544, 1496)

# K-Nearest Neighbors Model

In [36]:
# Imports

from sklearn.neighbors import NearestNeighbors

In [37]:
# Instantiating & fitting model to dtm

knn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
knn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

## Testing Trained KNN Model on Test Input

In [81]:
test_input = 'I want a strain that would make me relaxed and euphoric as well as sleepy'

In [39]:
# vect = TfidfVectorizer(stop_words="english", min_df=0.025, max_df=0.98, ngram_range=(1,3))

In [82]:
# Tokenizing User Input

test_input = tokenize(test_input)

In [83]:
# Vectorizing & Processing Raw Test Input

test_input = vect.transform(test_input)

In [84]:
test_input = test_input.todense()

In [85]:
test_input.shape

(5, 470)

In [86]:
dtm.shape

(2280, 470)

In [87]:
# Calculating Predicted Strains

predictions = knn.kneighbors(test_input)

In [88]:
predictions

(array([[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.22065742, 1.22586952, 1.23226439, 1.23255444, 1.2327771 ],
        [1.29685671, 1.30250781, 1.30450287, 1.30723764, 1.31413888],
        [1.29311847, 1.29321211, 1.29874137, 1.29969628, 1.2996996 ],
        [1.2305507 , 1.23129812, 1.24715442, 1.25019384, 1.26702328]]),
 array([[1431,  337,  833, 1687, 2111],
        [1805, 1831,  176,  768,  967],
        [ 683, 2019, 1061, 2253, 2175],
        [1019, 1783, 1596,  387, 1688],
        [2269, 1734,  753,  466, 1907]]))

In [89]:
# Top 5 Predictions

predictions[1][0]

array([1431,  337,  833, 1687, 2111])

In [90]:
top_match = predictions[1][0][0]

In [91]:
top_match

1431

In [92]:
output = df_strains.iloc[top_match]

In [93]:
output.drop(['name', 'ailment', 'all_text', 'lemmas', 'Cos Sim Strains']).to_dict()

{'index': 1431,
 'Strain': 'Nightmare-Cookies',
 'Type': 'hybrid',
 'Effects': 'Relaxed,Euphoric,Happy,Creative,Uplifted',
 'Flavor': 'Sweet,Pine,Woody',
 'Description': 'The commonsense cross of White Nightmare and Girl Scout Cookies, Nightmare Cookies is a hybrid strain that locks the consumer to the couch while delivering robust, uplifting euphoria. Nightmare Cookies exhibits beautiful purple hues, bright orange pistils, and an aroma that is thick with pine sap, earth, and sweetness. Enjoy this strain toward the end of the day to capitalize on its relaxing effects, appetite stimulation, and overall sedation.\xa0'}

## Creating & Testing DataBase in MongoDB

In [52]:
# from pymongo import MongoClient

In [53]:
# # Mongo Credentials

# MONGODB_USER = 'pot_head'
# MONGODB_PASS = 'vSSweD3UfaPfLbCl'
# MONGODB_URI = 'cannabis.plrhi.mongodb.net'

In [56]:
# client = MongoClient(f"mongodb+srv://{MONGODB_USER}:{MONGODB_PASS}@{MONGODB_URI}/<dbname>?retryWrites=true&w=majority").MEDCABU4.cannabis
# db = client.test

In [57]:
# db

Collection(Database(MongoClient(host=['cannabis-shard-00-00.plrhi.mongodb.net:27017', 'cannabis-shard-00-01.plrhi.mongodb.net:27017', 'cannabis-shard-00-02.plrhi.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-kv69op-shard-0', ssl=True), 'MEDCABU4'), 'cannabis.test')

## Testing User Input on Cosine Similarity Model

In [94]:
# Instantiating & Fitting Cosine Similarity using Nearest Neighbors Model

cnn = NearestNeighbors(n_neighbors=5, metric='cosine')
cnn.fit(dtm)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [60]:
import spacy.cli
spacy.cli.download("en_core_web_sm")

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')


In [61]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [62]:
# Function for Tokenizing User Input

def tokenize(document):
    doc = nlp(document)
    return [token.lemma_.strip() for token in doc if (token.is_stop != True) and (token.is_punct != True)]

In [96]:
test_input = 'I want a strain that would make me relaxed and euphoric as well as sleepy'

In [97]:
# Tokenizing User Input

test_input = tokenize(test_input)

In [98]:
# Vectorizing User Input

test_input = vect.transform(test_input)

In [99]:
test_input = test_input.todense()

In [100]:
test_input

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [101]:
prediction = cnn.kneighbors(test_input)

In [102]:
best_match = prediction[1][0][0]

In [103]:
output = df_strains.iloc[best_match]

In [104]:
output.drop(['name', 'ailment', 'all_text', 'lemmas', 'Cos Sim Strains']).to_dict()

{'index': 1519,
 'Strain': 'Panama-Red',
 'Type': 'sativa',
 'Effects': 'Happy,Hungry,Uplifted,Energetic,Focused',
 'Flavor': 'Earthy,Spicy/Herbal,Skunk',
 'Description': 'Panama Red is best described as an old-school cannabis classic. Originating from Panama, this pure sativa rose to stardom in the late 1960’s thanks to its typical sativa effects: speedy and intense, bordering on psychedelic. As cannabis cultivation matured, Panama Red, which has a lengthy flowering time of at least 11 weeks, was left behind for faster growing strains and increased profits. However, those who fondly recall days of its prominence love its smooth medicating experience and loftily contemplate its revival. If you can get your hands on this sentimental throwback, do not hesitate to groove down memory lane and enjoy the ride.'}